name: Add a commit

on:
  push:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 1
          
      - shell: bash
        run: |
          expr 3 + 7 > .github/writefile.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '.github/writefile.txt'
          message: 'Updated the writefile!'
