name: Validate PR Comment

on:
  issue_comment:

jobs:
  validate:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event.issue.pull_request }}
        echo ${{ github.event.issue.pull_request.head }}
        echo ${{ github.event.issue.pull_request.head.sha }}
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.issue.pull_request.head.sha }}

    - name: 🐍 Setting Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt
          python .github/validate_comment.py --body ${{ github.event.comment.body }}
          if [ $? -ne 0 ]; then
            echo "Validation failed!"
            exit 1
          fi
