name: Validate PR Comment

on:
  push:
  issue_comment:
    types: [created, edited]

jobs:
  validate:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - run: |
          echo ${{ github.event.comment.body }}
