name: Validate PR Comment

on:
  issue_comment:

jobs:
  validate:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.issue.pull_request.head.sha }}

    - name: 🐍 Setting Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

    - run: |
          echo ${{ github.event.comment.body }}
