name: Check context
on:
  workflow_dispatch:
  issue_comment:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
