name: Publish on Release

on:
  release:
    types: [published]

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Set env
        run: echo "NUGET_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - run: dotnet build -c release -p:Version=${{ env.NUGET_VERSION }}