name: Publish on Release

on:
  release:
    types: [published]
    
env:
  PROJECT_PATH: 'Pipeline.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Set env
        run: |
          echo "NUGET_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "NUGET_VERSION: ${{ env.NUGET_VERSION }}"
          echo "TAG: ${{ env.TAG }}"
