name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release
        
      - name: read release
        run: echo ${{ steps.release.outputs.tag_name }}
        
      - uses: eregon/publish-release@v1
        with:
          release_id: ${{ steps.release.outputs.id }}
