name: Tag release

on:
  release:
    types:
     - created
     - edited
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

env:
  tag: '0.0.0'
  release: 'success'

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 1
          
      - name: Set env Tag
        run: |
          if [[ ${{ github.event_name }} == 'release' ]]; then
              echo "env.tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
              echo "env.release=success" >> $GITHUB_ENV
          else
              echo "env.tag=${{ inputs.tag }}" >> $GITHUB_ENV
              echo "env.release=nosuccess" >> $GITHUB_ENV
          fi
          
  read_value:
     needs: update_version
     runs-on: ubuntu-latest
     steps:
      - name: release
        if: env.release == 'success'
        run: echo "You used a release and the tag is ${{ env.tag }}"
        
      - name: manual
        if: env.release == 'nosuccess'
        run: echo "You used a manual approach and the tag is ${{ env.tag }}"
