name: Create a yak page and push to azure
on: push

jobs:
  upload:
    runs-on: windows-latest
    steps:
      - name: 🛎 Checkout repo
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          
      - name: 📥 Download yak
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: curl -o ${{ github.workspace }}/yak.exe http://files.mcneel.com/yak/tools/latest/yak.exe

      - name: 📜 Display
        run: |
          foreach ($filename in $(ls ./images)) { echo $filename }
          #echo $(basename ./grasshoperYak)
